version: '2'
services:
  web:
    restart: on-failure
    # links:
    #  - db
    ports:
      - "80:9000"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      SESSION_SECRET: ${SESSION_SECRET}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_AUTH_URL: ${OIDC_AUTH_URL}
      OIDC_TOKEN_URL: ${OIDC_TOKEN_URL}
      OIDC_USERINFO_URL: ${OIDC_USERINFO_URL}
      OIDC_CALLBACK_URL: ${OIDC_CALLBACK_URL}
      OIDC_SCOPE: ${OIDC_SCOPE}
      MONGO_URL: mongodb://db:27017/mern-starter
  # db:
  #   image: mongo:latest
  #   ports:
  #    - "27017:27017"
